/*
 Navicat Premium Data Transfer

 Source Server         : PostgreSQL
 Source Server Type    : PostgreSQL
 Source Server Version : 160003 (160003)
 Source Host           : localhost:5432
 Source Catalog        : jHipsterMonolith
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160003 (160003)
 File Encoding         : 65001

 Date: 22/08/2024 12:04:56
*/


-- ----------------------------
-- Sequence structure for city_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "city_id_seq";
CREATE SEQUENCE "city_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for country_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "country_id_seq";
CREATE SEQUENCE "country_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for department_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "department_id_seq";
CREATE SEQUENCE "department_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for district_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "district_id_seq";
CREATE SEQUENCE "district_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for employee_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "employee_id_seq";
CREATE SEQUENCE "employee_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for jhi_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "jhi_user_id_seq";
CREATE SEQUENCE "jhi_user_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for job_history_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "job_history_id_seq";
CREATE SEQUENCE "job_history_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for job_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "job_id_seq";
CREATE SEQUENCE "job_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for location_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "location_id_seq";
CREATE SEQUENCE "location_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for postal_code_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "postal_code_id_seq";
CREATE SEQUENCE "postal_code_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for province_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "province_id_seq";
CREATE SEQUENCE "province_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for region_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "region_id_seq";
CREATE SEQUENCE "region_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sub_district_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "sub_district_id_seq";
CREATE SEQUENCE "sub_district_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for task_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "task_id_seq";
CREATE SEQUENCE "task_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for city
-- ----------------------------
DROP TABLE IF EXISTS "city";
CREATE TABLE "city" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "unm_49_code" varchar(255) COLLATE "pg_catalog"."default",
  "iso_alpha_2_code" varchar(255) COLLATE "pg_catalog"."default",
  "province_id" int8
)
;

-- ----------------------------
-- Records of city
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for country
-- ----------------------------
DROP TABLE IF EXISTS "country";
CREATE TABLE "country" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "unm_49_code" varchar(255) COLLATE "pg_catalog"."default",
  "iso_alpha_2_code" varchar(255) COLLATE "pg_catalog"."default",
  "region_id" int8
)
;

-- ----------------------------
-- Records of country
-- ----------------------------
BEGIN;
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (1, 'Algeria', NULL, 'DZ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (2, 'Angola', NULL, 'AO', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (3, 'Benin', NULL, 'BJ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (4, 'Botswana', NULL, 'BW', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (5, 'Burkina Faso', NULL, 'BF', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (6, 'Burundi', NULL, 'BI', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (7, 'Cabo Verde', NULL, 'CV', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (8, 'Cameroon', NULL, 'CM', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (9, 'Central African Republic', NULL, 'CF', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (10, 'Chad', NULL, 'TD', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (11, 'Comoros', NULL, 'KM', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (12, 'Congo (Congo-Brazzaville)', NULL, 'CG', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (13, 'Côte d''Ivoire', NULL, 'CI', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (14, 'Djibouti', NULL, 'DJ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (15, 'Egypt', NULL, 'EG', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (16, 'Equatorial Guinea', NULL, 'GQ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (17, 'Eritrea', NULL, 'ER', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (18, 'Eswatini', NULL, 'SZ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (19, 'Ethiopia', NULL, 'ET', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (20, 'Gabon', NULL, 'GA', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (21, 'Gambia', NULL, 'GM', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (22, 'Ghana', NULL, 'GH', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (23, 'Guinea', NULL, 'GN', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (24, 'Guinea-Bissau', NULL, 'GW', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (25, 'Kenya', NULL, 'KE', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (26, 'Lesotho', NULL, 'LS', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (27, 'Liberia', NULL, 'LR', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (28, 'Libya', NULL, 'LY', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (29, 'Madagascar', NULL, 'MG', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (30, 'Malawi', NULL, 'MW', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (31, 'Mali', NULL, 'ML', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (32, 'Mauritania', NULL, 'MR', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (33, 'Mauritius', NULL, 'MU', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (34, 'Morocco', NULL, 'MA', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (35, 'Mozambique', NULL, 'MZ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (36, 'Namibia', NULL, 'NA', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (37, 'Niger', NULL, 'NE', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (38, 'Nigeria', NULL, 'NG', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (39, 'Rwanda', NULL, 'RW', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (40, 'Sao Tome and Principe', NULL, 'ST', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (41, 'Senegal', NULL, 'SN', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (42, 'Seychelles', NULL, 'SC', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (43, 'Sierra Leone', NULL, 'SL', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (44, 'Somalia', NULL, 'SO', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (45, 'South Africa', NULL, 'ZA', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (46, 'South Sudan', NULL, 'SS', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (47, 'Sudan', NULL, 'SD', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (48, 'Tanzania', NULL, 'TZ', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (49, 'Togo', NULL, 'TG', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (50, 'Tunisia', NULL, 'TN', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (51, 'Uganda', NULL, 'UG', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (52, 'Zambia', NULL, 'ZM', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (53, 'Zimbabwe', NULL, 'ZW', 2);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (54, 'Argentina', NULL, 'AR', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (55, 'Bahamas', NULL, 'BS', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (56, 'Barbados', NULL, 'BB', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (57, 'Belize', NULL, 'BZ', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (58, 'Bolivia', NULL, 'BO', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (59, 'Brazil', NULL, 'BR', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (60, 'Canada', NULL, 'CA', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (61, 'Chile', NULL, 'CL', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (62, 'Colombia', NULL, 'CO', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (63, 'Costa Rica', NULL, 'CR', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (64, 'Cuba', NULL, 'CU', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (65, 'Dominica', NULL, 'DM', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (66, 'Dominican Republic', NULL, 'DO', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (67, 'Ecuador', NULL, 'EC', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (68, 'El Salvador', NULL, 'SV', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (69, 'Grenada', NULL, 'GD', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (70, 'Guatemala', NULL, 'GT', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (71, 'Guyana', NULL, 'GY', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (72, 'Haiti', NULL, 'HT', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (73, 'Honduras', NULL, 'HN', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (74, 'Jamaica', NULL, 'JM', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (75, 'Mexico', NULL, 'MX', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (76, 'Nicaragua', NULL, 'NI', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (77, 'Panama', NULL, 'PA', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (78, 'Paraguay', NULL, 'PY', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (79, 'Peru', NULL, 'PE', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (80, 'Saint Kitts and Nevis', NULL, 'KN', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (81, 'Saint Lucia', NULL, 'LC', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (82, 'Saint Vincent and the Grenadines', NULL, 'VC', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (83, 'Suriname', NULL, 'SR', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (84, 'Trinidad and Tobago', NULL, 'TT', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (85, 'United States of America', NULL, 'US', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (86, 'Uruguay', NULL, 'UY', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (87, 'Venezuela', NULL, 'VE', 9);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (88, 'Afghanistan', NULL, 'AF', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (89, 'Armenia', NULL, 'AM', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (90, 'Azerbaijan', NULL, 'AZ', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (91, 'Bahrain', NULL, 'BH', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (92, 'Bangladesh', NULL, 'BD', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (93, 'Bhutan', NULL, 'BT', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (94, 'Brunei Darussalam', NULL, 'BN', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (95, 'Cambodia', NULL, 'KH', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (96, 'China', NULL, 'CN', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (97, 'Georgia', NULL, 'GE', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (98, 'India', NULL, 'IN', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (99, 'Indonesia', NULL, 'ID', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (100, 'Iran', NULL, 'IR', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (101, 'Iraq', NULL, 'IQ', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (102, 'Israel', NULL, 'IL', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (103, 'Japan', NULL, 'JP', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (104, 'Jordan', NULL, 'JO', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (105, 'Kazakhstan', NULL, 'KZ', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (106, 'Kuwait', NULL, 'KW', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (107, 'Kyrgyzstan', NULL, 'KG', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (108, 'Lao PDR', NULL, 'LA', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (109, 'Lebanon', NULL, 'LB', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (110, 'Malaysia', NULL, 'MY', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (111, 'Maldives', NULL, 'MV', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (112, 'Mongolia', NULL, 'MN', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (113, 'Myanmar', NULL, 'MM', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (114, 'Nepal', NULL, 'NP', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (115, 'Oman', NULL, 'OM', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (116, 'Pakistan', NULL, 'PK', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (117, 'Philippines', NULL, 'PH', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (118, 'Qatar', NULL, 'QA', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (119, 'Republic of Korea', NULL, 'KR', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (120, 'Saudi Arabia', NULL, 'SA', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (121, 'Singapore', NULL, 'SG', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (122, 'Sri Lanka', NULL, 'LK', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (123, 'Syrian Arab Republic', NULL, 'SY', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (124, 'Tajikistan', NULL, 'TJ', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (125, 'Thailand', NULL, 'TH', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (126, 'Timor-Leste', NULL, 'TL', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (127, 'Turkey', NULL, 'TR', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (128, 'Turkmenistan', NULL, 'TM', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (129, 'United Arab Emirates', NULL, 'AE', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (130, 'Uzbekistan', NULL, 'UZ', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (131, 'Viet Nam', NULL, 'VN', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (132, 'Yemen', NULL, 'YE', 15);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (133, 'Albania', NULL, 'AL', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (134, 'Andorra', NULL, 'AD', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (135, 'Austria', NULL, 'AT', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (136, 'Belarus', NULL, 'BY', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (137, 'Belgium', NULL, 'BE', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (138, 'Bosnia and Herzegovina', NULL, 'BA', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (139, 'Bulgaria', NULL, 'BG', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (140, 'Croatia', NULL, 'HR', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (141, 'Cyprus', NULL, 'CY', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (142, 'Czech Republic', NULL, 'CZ', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (143, 'Denmark', NULL, 'DK', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (144, 'Estonia', NULL, 'EE', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (145, 'Finland', NULL, 'FI', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (146, 'France', NULL, 'FR', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (147, 'Germany', NULL, 'DE', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (148, 'Greece', NULL, 'GR', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (149, 'Hungary', NULL, 'HU', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (150, 'Iceland', NULL, 'IS', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (151, 'Ireland', NULL, 'IE', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (152, 'Italy', NULL, 'IT', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (153, 'Kosovo', NULL, 'XK', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (154, 'Latvia', NULL, 'LV', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (155, 'Liechtenstein', NULL, 'LI', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (156, 'Lithuania', NULL, 'LT', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (157, 'Luxembourg', NULL, 'LU', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (158, 'Malta', NULL, 'MT', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (159, 'Moldova', NULL, 'MD', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (160, 'Monaco', NULL, 'MC', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (161, 'Montenegro', NULL, 'ME', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (162, 'Netherlands', NULL, 'NL', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (163, 'North Macedonia', NULL, 'MK', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (164, 'Norway', NULL, 'NO', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (165, 'Poland', NULL, 'PL', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (166, 'Portugal', NULL, 'PT', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (167, 'Romania', NULL, 'RO', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (168, 'Russian Federation', NULL, 'RU', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (169, 'San Marino', NULL, 'SM', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (170, 'Serbia', NULL, 'RS', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (171, 'Slovakia', NULL, 'SK', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (172, 'Slovenia', NULL, 'SI', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (173, 'Spain', NULL, 'ES', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (174, 'Sweden', NULL, 'SE', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (175, 'Switzerland', NULL, 'CH', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (176, 'Ukraine', NULL, 'UA', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (177, 'United Kingdom', NULL, 'GB', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (178, 'Vatican City', NULL, 'VA', 21);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (179, 'Australia', NULL, 'AU', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (180, 'Fiji', NULL, 'FJ', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (181, 'Kiribati', NULL, 'KI', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (182, 'Marshall Islands', NULL, 'MH', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (183, 'Micronesia (Federated States of)', NULL, 'FM', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (184, 'Nauru', NULL, 'NR', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (185, 'New Zealand', NULL, 'NZ', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (186, 'Palau', NULL, 'PW', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (187, 'Papua New Guinea', NULL, 'PG', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (188, 'Samoa', NULL, 'WS', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (189, 'Solomon Islands', NULL, 'SB', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (190, 'Tonga', NULL, 'TO', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (191, 'Tuvalu', NULL, 'TV', 26);
INSERT INTO "country" ("id", "name", "unm_49_code", "iso_alpha_2_code", "region_id") VALUES (192, 'Vanuatu', NULL, 'VU', 26);
COMMIT;

-- ----------------------------
-- Table structure for databasechangelog
-- ----------------------------
DROP TABLE IF EXISTS "databasechangelog";
CREATE TABLE "databasechangelog" (
  "id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "author" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "filename" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "dateexecuted" timestamp(6) NOT NULL,
  "orderexecuted" int4 NOT NULL,
  "exectype" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  "md5sum" varchar(35) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "comments" varchar(255) COLLATE "pg_catalog"."default",
  "tag" varchar(255) COLLATE "pg_catalog"."default",
  "liquibase" varchar(20) COLLATE "pg_catalog"."default",
  "contexts" varchar(255) COLLATE "pg_catalog"."default",
  "labels" varchar(255) COLLATE "pg_catalog"."default",
  "deployment_id" varchar(10) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of databasechangelog
-- ----------------------------
BEGIN;
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('00000000000001', 'jhipster', 'config/liquibase/changelog/00000000000000_initial_schema.xml', '2024-08-22 10:54:41.017887', 1, 'EXECUTED', '9:792ed4e40e4a698b9cc9506d5abf4972', 'createTable tableName=jhi_user; createTable tableName=jhi_authority; createTable tableName=jhi_user_authority; addPrimaryKey tableName=jhi_user_authority; addForeignKeyConstraint baseTableName=jhi_user_authority, constraintName=fk_authority_name, ...', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094136-1', 'jhipster', 'config/liquibase/changelog/20240816094136_added_entity_Region.xml', '2024-08-22 10:54:41.068894', 2, 'EXECUTED', '9:11ec79f8b5a517558fc921a74c017bc4', 'createTable tableName=region', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094136-1-data', 'jhipster', 'config/liquibase/changelog/20240816094136_added_entity_Region.xml', '2024-08-22 10:54:41.1132', 3, 'EXECUTED', '9:f37a87e85fc0062d945f2a63c2e30dba', 'loadData tableName=region', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094137-1', 'jhipster', 'config/liquibase/changelog/20240816094137_added_entity_Country.xml', '2024-08-22 10:54:41.151065', 4, 'EXECUTED', '9:95fc73fa83d69b2a8592fee9e10e3474', 'createTable tableName=country', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094137-1-data', 'jhipster', 'config/liquibase/changelog/20240816094137_added_entity_Country.xml', '2024-08-22 10:54:41.192841', 5, 'EXECUTED', '9:77d451313fdf96eb87217889c69bc323', 'loadData tableName=country', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094138-1', 'jhipster', 'config/liquibase/changelog/20240816094138_added_entity_Location.xml', '2024-08-22 10:54:41.22553', 6, 'EXECUTED', '9:286b831ba5f7a89050d4b18950e0d93f', 'createTable tableName=location', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094138-1-data', 'jhipster', 'config/liquibase/changelog/20240816094138_added_entity_Location.xml', '2024-08-22 10:54:41.26408', 7, 'EXECUTED', '9:26a926c7a19002e0d4597788e874e55a', 'loadData tableName=location', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094139-1', 'jhipster', 'config/liquibase/changelog/20240816094139_added_entity_Department.xml', '2024-08-22 10:54:41.294387', 8, 'EXECUTED', '9:b381b28c93f9faea4fb309f1fa1574da', 'createTable tableName=department', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094139-1-data', 'jhipster', 'config/liquibase/changelog/20240816094139_added_entity_Department.xml', '2024-08-22 10:54:41.330526', 9, 'EXECUTED', '9:510db9e846fc1cb7770ec0d84cd84c3a', 'loadData tableName=department', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094140-1', 'jhipster', 'config/liquibase/changelog/20240816094140_added_entity_Task.xml', '2024-08-22 10:54:41.362752', 10, 'EXECUTED', '9:369bae343a4720f9f7e6dfdf09741bff', 'createTable tableName=task', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094140-1-data', 'jhipster', 'config/liquibase/changelog/20240816094140_added_entity_Task.xml', '2024-08-22 10:54:41.403129', 11, 'EXECUTED', '9:fe14fa37c589ab0a741b881fa7c074e2', 'loadData tableName=task', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094141-1', 'jhipster', 'config/liquibase/changelog/20240816094141_added_entity_Employee.xml', '2024-08-22 10:54:41.441714', 12, 'EXECUTED', '9:a5c1425a45473b60a6799bbcb5e50628', 'createTable tableName=employee; dropDefaultValue columnName=hire_date, tableName=employee', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094141-1-data', 'jhipster', 'config/liquibase/changelog/20240816094141_added_entity_Employee.xml', '2024-08-22 10:54:41.498674', 13, 'EXECUTED', '9:4ff9f5afcd37c32d16a62be98d1eacd3', 'loadData tableName=employee', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094142-1', 'jhipster', 'config/liquibase/changelog/20240816094142_added_entity_Job.xml', '2024-08-22 10:54:41.523087', 14, 'EXECUTED', '9:8e7c559dc681e8034131ad01bed4a8cf', 'createTable tableName=job', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094142-1-relations', 'jhipster', 'config/liquibase/changelog/20240816094142_added_entity_Job.xml', '2024-08-22 10:54:41.552818', 15, 'EXECUTED', '9:e7cc8f9e785e47e10d35a4ea9df9e5d2', 'createTable tableName=rel_job__task; addPrimaryKey tableName=rel_job__task', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094142-1-data', 'jhipster', 'config/liquibase/changelog/20240816094142_added_entity_Job.xml', '2024-08-22 10:54:41.603229', 16, 'EXECUTED', '9:3ea952aab73f88ce001e14472c0a4b15', 'loadData tableName=job', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094143-1', 'jhipster', 'config/liquibase/changelog/20240816094143_added_entity_JobHistory.xml', '2024-08-22 10:54:41.671762', 17, 'EXECUTED', '9:e62e5894302a03975ea7f88da79cf140', 'createTable tableName=job_history; dropDefaultValue columnName=start_date, tableName=job_history; dropDefaultValue columnName=end_date, tableName=job_history', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094143-1-data', 'jhipster', 'config/liquibase/changelog/20240816094143_added_entity_JobHistory.xml', '2024-08-22 10:54:41.741578', 18, 'EXECUTED', '9:3830497c1fb754d639898a7590cf080a', 'loadData tableName=job_history', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021640-1', 'jhipster', 'config/liquibase/changelog/20240821021640_added_entity_Province.xml', '2024-08-22 10:54:41.794129', 19, 'EXECUTED', '9:4a5fe2198f103c5b573cf4d653ec7b5d', 'createTable tableName=province', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021640-1-data', 'jhipster', 'config/liquibase/changelog/20240821021640_added_entity_Province.xml', '2024-08-22 10:54:41.845128', 20, 'EXECUTED', '9:f9780a4ff8c4ba44504a6acdc1b8a83e', 'loadData tableName=province', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021641-1', 'jhipster', 'config/liquibase/changelog/20240821021641_added_entity_City.xml', '2024-08-22 10:54:41.894634', 21, 'EXECUTED', '9:a4e9f77401c90a5bf26a2d0183d50aca', 'createTable tableName=city', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021641-1-data', 'jhipster', 'config/liquibase/changelog/20240821021641_added_entity_City.xml', '2024-08-22 10:54:41.940152', 22, 'EXECUTED', '9:d366e7cd909f5d892947d00ab17d3954', 'loadData tableName=city', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021642-1', 'jhipster', 'config/liquibase/changelog/20240821021642_added_entity_District.xml', '2024-08-22 10:54:41.984229', 23, 'EXECUTED', '9:1b9be3d120d9851231d2df0a3fc96b8b', 'createTable tableName=district', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021642-1-data', 'jhipster', 'config/liquibase/changelog/20240821021642_added_entity_District.xml', '2024-08-22 10:54:42.024146', 24, 'EXECUTED', '9:fa28664b5beb6554d1c0a79a40db1c5d', 'loadData tableName=district', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021643-1', 'jhipster', 'config/liquibase/changelog/20240821021643_added_entity_SubDistrict.xml', '2024-08-22 10:54:42.063762', 25, 'EXECUTED', '9:2ea9513821720db3c14715bff2791d79', 'createTable tableName=sub_district', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021643-1-data', 'jhipster', 'config/liquibase/changelog/20240821021643_added_entity_SubDistrict.xml', '2024-08-22 10:54:42.100365', 26, 'EXECUTED', '9:10aa1d8ea3df4c185f7d768896aa9f38', 'loadData tableName=sub_district', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021644-1', 'jhipster', 'config/liquibase/changelog/20240821021644_added_entity_PostalCode.xml', '2024-08-22 10:54:42.126419', 27, 'EXECUTED', '9:ac423952c481e21da43e9a317af45d34', 'createTable tableName=postal_code', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021644-1-data', 'jhipster', 'config/liquibase/changelog/20240821021644_added_entity_PostalCode.xml', '2024-08-22 10:54:42.160164', 28, 'EXECUTED', '9:4a6ba1fd6abd753eaa7eaecf7837f764', 'loadData tableName=postal_code', '', NULL, '4.27.0', 'faker', NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094137-2', 'jhipster', 'config/liquibase/changelog/20240816094137_added_entity_constraints_Country.xml', '2024-08-22 10:54:42.175743', 29, 'EXECUTED', '9:9c48363819c2585ed3bd3cb1d5739ee8', 'addForeignKeyConstraint baseTableName=country, constraintName=fk_country__region_id, referencedTableName=region', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094139-2', 'jhipster', 'config/liquibase/changelog/20240816094139_added_entity_constraints_Department.xml', '2024-08-22 10:54:42.192926', 30, 'EXECUTED', '9:1a15a598647a6e82a5b731effb8bf7cb', 'addForeignKeyConstraint baseTableName=department, constraintName=fk_department__location_id, referencedTableName=location', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094141-2', 'jhipster', 'config/liquibase/changelog/20240816094141_added_entity_constraints_Employee.xml', '2024-08-22 10:54:42.212384', 31, 'EXECUTED', '9:7fda3264ac6abf9335d087084fbea7c5', 'addForeignKeyConstraint baseTableName=employee, constraintName=fk_employee__manager_id, referencedTableName=employee; addForeignKeyConstraint baseTableName=employee, constraintName=fk_employee__department_id, referencedTableName=department', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094142-2', 'jhipster', 'config/liquibase/changelog/20240816094142_added_entity_constraints_Job.xml', '2024-08-22 10:54:42.236707', 32, 'EXECUTED', '9:1d2ba43597f393ea1c7486b06fea684c', 'addForeignKeyConstraint baseTableName=rel_job__task, constraintName=fk_rel_job__task__job_id, referencedTableName=job; addForeignKeyConstraint baseTableName=rel_job__task, constraintName=fk_rel_job__task__task_id, referencedTableName=task; addFore...', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240816094143-2', 'jhipster', 'config/liquibase/changelog/20240816094143_added_entity_constraints_JobHistory.xml', '2024-08-22 10:54:42.262535', 33, 'EXECUTED', '9:e32eee50596b1067d2db8de7649ebf4a', 'addForeignKeyConstraint baseTableName=job_history, constraintName=fk_job_history__job_id, referencedTableName=job; addForeignKeyConstraint baseTableName=job_history, constraintName=fk_job_history__department_id, referencedTableName=department; add...', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021640-2', 'jhipster', 'config/liquibase/changelog/20240821021640_added_entity_constraints_Province.xml', '2024-08-22 10:54:42.278216', 34, 'EXECUTED', '9:4c70bfe2c3938ef54223b29203221884', 'addForeignKeyConstraint baseTableName=province, constraintName=fk_province__country_id, referencedTableName=country', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021641-2', 'jhipster', 'config/liquibase/changelog/20240821021641_added_entity_constraints_City.xml', '2024-08-22 10:54:42.293064', 35, 'EXECUTED', '9:ceebe62cd153b228cee29aac4d621a6f', 'addForeignKeyConstraint baseTableName=city, constraintName=fk_city__province_id, referencedTableName=province', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021642-2', 'jhipster', 'config/liquibase/changelog/20240821021642_added_entity_constraints_District.xml', '2024-08-22 10:54:42.307733', 36, 'EXECUTED', '9:973a78ffcdde5649d70b460b3be9e3e7', 'addForeignKeyConstraint baseTableName=district, constraintName=fk_district__city_id, referencedTableName=city', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021643-2', 'jhipster', 'config/liquibase/changelog/20240821021643_added_entity_constraints_SubDistrict.xml', '2024-08-22 10:54:42.322323', 37, 'EXECUTED', '9:aff9428489c24c1100eef1c65f53be74', 'addForeignKeyConstraint baseTableName=sub_district, constraintName=fk_sub_district__district_id, referencedTableName=district', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821021644-2', 'jhipster', 'config/liquibase/changelog/20240821021644_added_entity_constraints_PostalCode.xml', '2024-08-22 10:54:42.337519', 38, 'EXECUTED', '9:9b7709608aca4ef316142ce60475add5', 'addForeignKeyConstraint baseTableName=postal_code, constraintName=fk_postal_code__sub_district_id, referencedTableName=sub_district', '', NULL, '4.27.0', NULL, NULL, '4298880607');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821190500-1-data', 'jhipster', 'config/liquibase/changelog/20240821190500_added_data_Region.xml', '2024-08-22 10:55:46.395524', 39, 'EXECUTED', '9:93e0e755c28b996bf064a4a8c4a8e978', 'loadData tableName=region', '', NULL, '4.27.0', NULL, NULL, '4298946315');
INSERT INTO "databasechangelog" ("id", "author", "filename", "dateexecuted", "orderexecuted", "exectype", "md5sum", "description", "comments", "tag", "liquibase", "contexts", "labels", "deployment_id") VALUES ('20240821194400-1-data', 'jhipster', 'config/liquibase/changelog/20240821194400_added_data_Country.xml', '2024-08-22 10:55:46.774615', 40, 'EXECUTED', '9:3938852341fc1b2dbe33f99bad9f6195', 'loadData tableName=country', '', NULL, '4.27.0', NULL, NULL, '4298946315');
COMMIT;

-- ----------------------------
-- Table structure for databasechangeloglock
-- ----------------------------
DROP TABLE IF EXISTS "databasechangeloglock";
CREATE TABLE "databasechangeloglock" (
  "id" int4 NOT NULL,
  "locked" bool NOT NULL,
  "lockgranted" timestamp(6),
  "lockedby" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of databasechangeloglock
-- ----------------------------
BEGIN;
INSERT INTO "databasechangeloglock" ("id", "locked", "lockgranted", "lockedby") VALUES (1, 'f', NULL, NULL);
COMMIT;

-- ----------------------------
-- Table structure for department
-- ----------------------------
DROP TABLE IF EXISTS "department";
CREATE TABLE "department" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "department_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "location_id" int8
)
;

-- ----------------------------
-- Records of department
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for district
-- ----------------------------
DROP TABLE IF EXISTS "district";
CREATE TABLE "district" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "unm_49_code" varchar(255) COLLATE "pg_catalog"."default",
  "iso_alpha_2_code" varchar(255) COLLATE "pg_catalog"."default",
  "city_id" int8
)
;

-- ----------------------------
-- Records of district
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for employee
-- ----------------------------
DROP TABLE IF EXISTS "employee";
CREATE TABLE "employee" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "first_name" varchar(255) COLLATE "pg_catalog"."default",
  "last_name" varchar(255) COLLATE "pg_catalog"."default",
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "phone_number" varchar(255) COLLATE "pg_catalog"."default",
  "hire_date" timestamp(6),
  "salary" int8,
  "commission_pct" int8,
  "manager_id" int8,
  "department_id" int8
)
;
COMMENT ON COLUMN "employee"."first_name" IS 'The firstname attribute.';
COMMENT ON TABLE "employee" IS 'The Employee entity.';

-- ----------------------------
-- Records of employee
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for jhi_authority
-- ----------------------------
DROP TABLE IF EXISTS "jhi_authority";
CREATE TABLE "jhi_authority" (
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of jhi_authority
-- ----------------------------
BEGIN;
INSERT INTO "jhi_authority" ("name") VALUES ('ROLE_ADMIN');
INSERT INTO "jhi_authority" ("name") VALUES ('ROLE_USER');
COMMIT;

-- ----------------------------
-- Table structure for jhi_user
-- ----------------------------
DROP TABLE IF EXISTS "jhi_user";
CREATE TABLE "jhi_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "login" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "password_hash" varchar(60) COLLATE "pg_catalog"."default" NOT NULL,
  "first_name" varchar(50) COLLATE "pg_catalog"."default",
  "last_name" varchar(50) COLLATE "pg_catalog"."default",
  "email" varchar(191) COLLATE "pg_catalog"."default",
  "image_url" varchar(256) COLLATE "pg_catalog"."default",
  "activated" bool NOT NULL,
  "lang_key" varchar(10) COLLATE "pg_catalog"."default",
  "activation_key" varchar(20) COLLATE "pg_catalog"."default",
  "reset_key" varchar(20) COLLATE "pg_catalog"."default",
  "created_by" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "created_date" timestamp(6),
  "reset_date" timestamp(6),
  "last_modified_by" varchar(50) COLLATE "pg_catalog"."default",
  "last_modified_date" timestamp(6)
)
;

-- ----------------------------
-- Records of jhi_user
-- ----------------------------
BEGIN;
INSERT INTO "jhi_user" ("id", "login", "password_hash", "first_name", "last_name", "email", "image_url", "activated", "lang_key", "activation_key", "reset_key", "created_by", "created_date", "reset_date", "last_modified_by", "last_modified_date") VALUES (1, 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', 't', 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL);
INSERT INTO "jhi_user" ("id", "login", "password_hash", "first_name", "last_name", "email", "image_url", "activated", "lang_key", "activation_key", "reset_key", "created_by", "created_date", "reset_date", "last_modified_by", "last_modified_date") VALUES (2, 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', 't', 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL);
COMMIT;

-- ----------------------------
-- Table structure for jhi_user_authority
-- ----------------------------
DROP TABLE IF EXISTS "jhi_user_authority";
CREATE TABLE "jhi_user_authority" (
  "user_id" int8 NOT NULL,
  "authority_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of jhi_user_authority
-- ----------------------------
BEGIN;
INSERT INTO "jhi_user_authority" ("user_id", "authority_name") VALUES (1, 'ROLE_ADMIN');
INSERT INTO "jhi_user_authority" ("user_id", "authority_name") VALUES (1, 'ROLE_USER');
INSERT INTO "jhi_user_authority" ("user_id", "authority_name") VALUES (2, 'ROLE_USER');
COMMIT;

-- ----------------------------
-- Table structure for job
-- ----------------------------
DROP TABLE IF EXISTS "job";
CREATE TABLE "job" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_title" varchar(255) COLLATE "pg_catalog"."default",
  "min_salary" int8,
  "max_salary" int8,
  "employee_id" int8
)
;

-- ----------------------------
-- Records of job
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for job_history
-- ----------------------------
DROP TABLE IF EXISTS "job_history";
CREATE TABLE "job_history" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "start_date" timestamp(6),
  "end_date" timestamp(6),
  "language" varchar(255) COLLATE "pg_catalog"."default",
  "job_id" int8,
  "department_id" int8,
  "employee_id" int8
)
;

-- ----------------------------
-- Records of job_history
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for location
-- ----------------------------
DROP TABLE IF EXISTS "location";
CREATE TABLE "location" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "street_address" varchar(255) COLLATE "pg_catalog"."default",
  "postal_code" varchar(255) COLLATE "pg_catalog"."default",
  "city" varchar(255) COLLATE "pg_catalog"."default",
  "state_province" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON TABLE "location" IS 'not an ignored comment';

-- ----------------------------
-- Records of location
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for postal_code
-- ----------------------------
DROP TABLE IF EXISTS "postal_code";
CREATE TABLE "postal_code" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "code" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "sub_district_id" int8
)
;

-- ----------------------------
-- Records of postal_code
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for province
-- ----------------------------
DROP TABLE IF EXISTS "province";
CREATE TABLE "province" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "unm_49_code" varchar(255) COLLATE "pg_catalog"."default",
  "iso_alpha_2_code" varchar(255) COLLATE "pg_catalog"."default",
  "country_id" int8
)
;

-- ----------------------------
-- Records of province
-- ----------------------------
BEGIN;
INSERT INTO "province" ("id", "name", "unm_49_code", "iso_alpha_2_code", "country_id") VALUES (1, 'Adrar ', NULL, '01', 1);
INSERT INTO "province" ("id", "name", "unm_49_code", "iso_alpha_2_code", "country_id") VALUES (2, 'Chlef ', NULL, '02', 1);
INSERT INTO "province" ("id", "name", "unm_49_code", "iso_alpha_2_code", "country_id") VALUES (3, 'Laghouat ', NULL, '03', 1);
INSERT INTO "province" ("id", "name", "unm_49_code", "iso_alpha_2_code", "country_id") VALUES (4, 'Oum El Bouaghi', NULL, '04', 1);
COMMIT;

-- ----------------------------
-- Table structure for region
-- ----------------------------
DROP TABLE IF EXISTS "region";
CREATE TABLE "region" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "unm_49_code" varchar(255) COLLATE "pg_catalog"."default",
  "iso_alpha_2_code" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of region
-- ----------------------------
BEGIN;
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (1, 'World', '001', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (2, 'Africa', '002', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (3, 'Northern Africa', '015', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (4, 'Sub-Saharan Africa', '202', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (5, 'Eastern Africa', '014', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (6, 'Middle Africa', '017', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (7, 'Southern Africa', '018', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (8, 'Western Africa', '011', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (9, 'Americas', '019', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (10, 'Latin America and the Caribbean', '419', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (11, 'Caribbean', '029', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (12, 'Central America', '013', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (13, 'South America', '005', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (14, 'Northern America', '021', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (15, 'Asia', '142', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (16, 'Central Asia', '143', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (17, 'Eastern Asia', '030', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (18, 'South-Eastern Asia', '035', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (19, 'Southern Asia', '034', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (20, 'Western Asia', '145', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (21, 'Europe', '150', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (22, 'Eastern Europe', '151', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (23, 'Northern Europe', '154', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (24, 'Southern Europe', '039', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (25, 'Western Europe', '155', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (26, 'Oceania', '009', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (27, 'Australia and New Zealand', '053', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (28, 'Melanesia', '054', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (29, 'Micronesia', '057', NULL);
INSERT INTO "region" ("id", "name", "unm_49_code", "iso_alpha_2_code") VALUES (30, 'Polynesia', '061', NULL);
COMMIT;

-- ----------------------------
-- Table structure for rel_job__task
-- ----------------------------
DROP TABLE IF EXISTS "rel_job__task";
CREATE TABLE "rel_job__task" (
  "task_id" int8 NOT NULL,
  "job_id" int8 NOT NULL
)
;

-- ----------------------------
-- Records of rel_job__task
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for sub_district
-- ----------------------------
DROP TABLE IF EXISTS "sub_district";
CREATE TABLE "sub_district" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "unm_49_code" varchar(255) COLLATE "pg_catalog"."default",
  "iso_alpha_2_code" varchar(255) COLLATE "pg_catalog"."default",
  "district_id" int8
)
;

-- ----------------------------
-- Records of sub_district
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for task
-- ----------------------------
DROP TABLE IF EXISTS "task";
CREATE TABLE "task" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "title" varchar(255) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON TABLE "task" IS 'Task entity.\n@author The JHipster team.';

-- ----------------------------
-- Records of task
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "city_id_seq"
OWNED BY "city"."id";
SELECT setval('"city_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "country_id_seq"
OWNED BY "country"."id";
SELECT setval('"country_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "department_id_seq"
OWNED BY "department"."id";
SELECT setval('"department_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "district_id_seq"
OWNED BY "district"."id";
SELECT setval('"district_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "employee_id_seq"
OWNED BY "employee"."id";
SELECT setval('"employee_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "jhi_user_id_seq"
OWNED BY "jhi_user"."id";
SELECT setval('"jhi_user_id_seq"', 1050, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "job_history_id_seq"
OWNED BY "job_history"."id";
SELECT setval('"job_history_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "job_id_seq"
OWNED BY "job"."id";
SELECT setval('"job_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "location_id_seq"
OWNED BY "location"."id";
SELECT setval('"location_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "postal_code_id_seq"
OWNED BY "postal_code"."id";
SELECT setval('"postal_code_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "province_id_seq"
OWNED BY "province"."id";
SELECT setval('"province_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "region_id_seq"
OWNED BY "region"."id";
SELECT setval('"region_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "sub_district_id_seq"
OWNED BY "sub_district"."id";
SELECT setval('"sub_district_id_seq"', 1500, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "task_id_seq"
OWNED BY "task"."id";
SELECT setval('"task_id_seq"', 1500, false);

-- ----------------------------
-- Auto increment value for city
-- ----------------------------
SELECT setval('"city_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table city
-- ----------------------------
ALTER TABLE "city" ADD CONSTRAINT "ux_city__unm_49_code" UNIQUE ("unm_49_code");
ALTER TABLE "city" ADD CONSTRAINT "ux_city__iso_alpha_2_code" UNIQUE ("iso_alpha_2_code");

-- ----------------------------
-- Primary Key structure for table city
-- ----------------------------
ALTER TABLE "city" ADD CONSTRAINT "city_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for country
-- ----------------------------
SELECT setval('"country_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table country
-- ----------------------------
ALTER TABLE "country" ADD CONSTRAINT "ux_country__unm_49_code" UNIQUE ("unm_49_code");
ALTER TABLE "country" ADD CONSTRAINT "ux_country__iso_alpha_2_code" UNIQUE ("iso_alpha_2_code");

-- ----------------------------
-- Primary Key structure for table country
-- ----------------------------
ALTER TABLE "country" ADD CONSTRAINT "country_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table databasechangeloglock
-- ----------------------------
ALTER TABLE "databasechangeloglock" ADD CONSTRAINT "databasechangeloglock_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for department
-- ----------------------------
SELECT setval('"department_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table department
-- ----------------------------
ALTER TABLE "department" ADD CONSTRAINT "ux_department__location_id" UNIQUE ("location_id");

-- ----------------------------
-- Primary Key structure for table department
-- ----------------------------
ALTER TABLE "department" ADD CONSTRAINT "department_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for district
-- ----------------------------
SELECT setval('"district_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table district
-- ----------------------------
ALTER TABLE "district" ADD CONSTRAINT "ux_district__unm_49_code" UNIQUE ("unm_49_code");
ALTER TABLE "district" ADD CONSTRAINT "ux_district__iso_alpha_2_code" UNIQUE ("iso_alpha_2_code");

-- ----------------------------
-- Primary Key structure for table district
-- ----------------------------
ALTER TABLE "district" ADD CONSTRAINT "district_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for employee
-- ----------------------------
SELECT setval('"employee_id_seq"', 1500, false);

-- ----------------------------
-- Primary Key structure for table employee
-- ----------------------------
ALTER TABLE "employee" ADD CONSTRAINT "employee_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table jhi_authority
-- ----------------------------
ALTER TABLE "jhi_authority" ADD CONSTRAINT "jhi_authority_pkey" PRIMARY KEY ("name");

-- ----------------------------
-- Auto increment value for jhi_user
-- ----------------------------
SELECT setval('"jhi_user_id_seq"', 1050, false);

-- ----------------------------
-- Uniques structure for table jhi_user
-- ----------------------------
ALTER TABLE "jhi_user" ADD CONSTRAINT "ux_user_login" UNIQUE ("login");
ALTER TABLE "jhi_user" ADD CONSTRAINT "ux_user_email" UNIQUE ("email");

-- ----------------------------
-- Primary Key structure for table jhi_user
-- ----------------------------
ALTER TABLE "jhi_user" ADD CONSTRAINT "jhi_user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table jhi_user_authority
-- ----------------------------
ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "jhi_user_authority_pkey" PRIMARY KEY ("user_id", "authority_name");

-- ----------------------------
-- Auto increment value for job
-- ----------------------------
SELECT setval('"job_id_seq"', 1500, false);

-- ----------------------------
-- Primary Key structure for table job
-- ----------------------------
ALTER TABLE "job" ADD CONSTRAINT "job_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for job_history
-- ----------------------------
SELECT setval('"job_history_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table job_history
-- ----------------------------
ALTER TABLE "job_history" ADD CONSTRAINT "ux_job_history__job_id" UNIQUE ("job_id");
ALTER TABLE "job_history" ADD CONSTRAINT "ux_job_history__department_id" UNIQUE ("department_id");
ALTER TABLE "job_history" ADD CONSTRAINT "ux_job_history__employee_id" UNIQUE ("employee_id");

-- ----------------------------
-- Primary Key structure for table job_history
-- ----------------------------
ALTER TABLE "job_history" ADD CONSTRAINT "job_history_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for location
-- ----------------------------
SELECT setval('"location_id_seq"', 1500, false);

-- ----------------------------
-- Primary Key structure for table location
-- ----------------------------
ALTER TABLE "location" ADD CONSTRAINT "location_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for postal_code
-- ----------------------------
SELECT setval('"postal_code_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table postal_code
-- ----------------------------
ALTER TABLE "postal_code" ADD CONSTRAINT "ux_postal_code__code" UNIQUE ("code");

-- ----------------------------
-- Primary Key structure for table postal_code
-- ----------------------------
ALTER TABLE "postal_code" ADD CONSTRAINT "postal_code_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for province
-- ----------------------------
SELECT setval('"province_id_seq"', 4, true);

-- ----------------------------
-- Uniques structure for table province
-- ----------------------------
ALTER TABLE "province" ADD CONSTRAINT "ux_province__unm_49_code" UNIQUE ("unm_49_code");
ALTER TABLE "province" ADD CONSTRAINT "ux_province__iso_alpha_2_code" UNIQUE ("iso_alpha_2_code");

-- ----------------------------
-- Primary Key structure for table province
-- ----------------------------
ALTER TABLE "province" ADD CONSTRAINT "province_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for region
-- ----------------------------
SELECT setval('"region_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table region
-- ----------------------------
ALTER TABLE "region" ADD CONSTRAINT "ux_region__unm_49_code" UNIQUE ("unm_49_code");
ALTER TABLE "region" ADD CONSTRAINT "ux_region__iso_alpha_2_code" UNIQUE ("iso_alpha_2_code");

-- ----------------------------
-- Primary Key structure for table region
-- ----------------------------
ALTER TABLE "region" ADD CONSTRAINT "region_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table rel_job__task
-- ----------------------------
ALTER TABLE "rel_job__task" ADD CONSTRAINT "rel_job__task_pkey" PRIMARY KEY ("job_id", "task_id");

-- ----------------------------
-- Auto increment value for sub_district
-- ----------------------------
SELECT setval('"sub_district_id_seq"', 1500, false);

-- ----------------------------
-- Uniques structure for table sub_district
-- ----------------------------
ALTER TABLE "sub_district" ADD CONSTRAINT "ux_sub_district__unm_49_code" UNIQUE ("unm_49_code");
ALTER TABLE "sub_district" ADD CONSTRAINT "ux_sub_district__iso_alpha_2_code" UNIQUE ("iso_alpha_2_code");

-- ----------------------------
-- Primary Key structure for table sub_district
-- ----------------------------
ALTER TABLE "sub_district" ADD CONSTRAINT "sub_district_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for task
-- ----------------------------
SELECT setval('"task_id_seq"', 1500, false);

-- ----------------------------
-- Primary Key structure for table task
-- ----------------------------
ALTER TABLE "task" ADD CONSTRAINT "task_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table city
-- ----------------------------
ALTER TABLE "city" ADD CONSTRAINT "fk_city__province_id" FOREIGN KEY ("province_id") REFERENCES "province" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table country
-- ----------------------------
ALTER TABLE "country" ADD CONSTRAINT "fk_country__region_id" FOREIGN KEY ("region_id") REFERENCES "region" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table department
-- ----------------------------
ALTER TABLE "department" ADD CONSTRAINT "fk_department__location_id" FOREIGN KEY ("location_id") REFERENCES "location" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table district
-- ----------------------------
ALTER TABLE "district" ADD CONSTRAINT "fk_district__city_id" FOREIGN KEY ("city_id") REFERENCES "city" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table employee
-- ----------------------------
ALTER TABLE "employee" ADD CONSTRAINT "fk_employee__department_id" FOREIGN KEY ("department_id") REFERENCES "department" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "employee" ADD CONSTRAINT "fk_employee__manager_id" FOREIGN KEY ("manager_id") REFERENCES "employee" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table jhi_user_authority
-- ----------------------------
ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "fk_authority_name" FOREIGN KEY ("authority_name") REFERENCES "jhi_authority" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "fk_user_id" FOREIGN KEY ("user_id") REFERENCES "jhi_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table job
-- ----------------------------
ALTER TABLE "job" ADD CONSTRAINT "fk_job__employee_id" FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table job_history
-- ----------------------------
ALTER TABLE "job_history" ADD CONSTRAINT "fk_job_history__department_id" FOREIGN KEY ("department_id") REFERENCES "department" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "job_history" ADD CONSTRAINT "fk_job_history__employee_id" FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "job_history" ADD CONSTRAINT "fk_job_history__job_id" FOREIGN KEY ("job_id") REFERENCES "job" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table postal_code
-- ----------------------------
ALTER TABLE "postal_code" ADD CONSTRAINT "fk_postal_code__sub_district_id" FOREIGN KEY ("sub_district_id") REFERENCES "sub_district" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table province
-- ----------------------------
ALTER TABLE "province" ADD CONSTRAINT "fk_province__country_id" FOREIGN KEY ("country_id") REFERENCES "country" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table rel_job__task
-- ----------------------------
ALTER TABLE "rel_job__task" ADD CONSTRAINT "fk_rel_job__task__job_id" FOREIGN KEY ("job_id") REFERENCES "job" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "rel_job__task" ADD CONSTRAINT "fk_rel_job__task__task_id" FOREIGN KEY ("task_id") REFERENCES "task" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table sub_district
-- ----------------------------
ALTER TABLE "sub_district" ADD CONSTRAINT "fk_sub_district__district_id" FOREIGN KEY ("district_id") REFERENCES "district" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
