package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstBrandAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstBrandAllPropertiesEquals(MstBrand expected, MstBrand actual) {
        assertMstBrandAutoGeneratedPropertiesEquals(expected, actual);
        assertMstBrandAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstBrandAllUpdatablePropertiesEquals(MstBrand expected, MstBrand actual) {
        assertMstBrandUpdatableFieldsEquals(expected, actual);
        assertMstBrandUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstBrandAutoGeneratedPropertiesEquals(MstBrand expected, MstBrand actual) {
        assertThat(expected)
            .as("Verify MstBrand auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstBrandUpdatableFieldsEquals(MstBrand expected, MstBrand actual) {
        assertThat(expected)
            .as("Verify MstBrand relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstBrandUpdatableRelationshipsEquals(MstBrand expected, MstBrand actual) {}
}
