package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstCityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCityAllPropertiesEquals(MstCity expected, MstCity actual) {
        assertMstCityAutoGeneratedPropertiesEquals(expected, actual);
        assertMstCityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCityAllUpdatablePropertiesEquals(MstCity expected, MstCity actual) {
        assertMstCityUpdatableFieldsEquals(expected, actual);
        assertMstCityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCityAutoGeneratedPropertiesEquals(MstCity expected, MstCity actual) {
        assertThat(expected)
            .as("Verify MstCity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCityUpdatableFieldsEquals(MstCity expected, MstCity actual) {
        assertThat(expected)
            .as("Verify MstCity relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getUnm49Code()).as("check unm49Code").isEqualTo(actual.getUnm49Code()))
            .satisfies(e -> assertThat(e.getIsoAlpha2Code()).as("check isoAlpha2Code").isEqualTo(actual.getIsoAlpha2Code()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCityUpdatableRelationshipsEquals(MstCity expected, MstCity actual) {
        assertThat(expected)
            .as("Verify MstCity relationships")
            .satisfies(e -> assertThat(e.getProvince()).as("check province").isEqualTo(actual.getProvince()));
    }
}
