package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCategoryAllPropertiesEquals(MstCategory expected, MstCategory actual) {
        assertMstCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMstCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCategoryAllUpdatablePropertiesEquals(MstCategory expected, MstCategory actual) {
        assertMstCategoryUpdatableFieldsEquals(expected, actual);
        assertMstCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCategoryAutoGeneratedPropertiesEquals(MstCategory expected, MstCategory actual) {
        assertThat(expected)
            .as("Verify MstCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCategoryUpdatableFieldsEquals(MstCategory expected, MstCategory actual) {
        assertThat(expected)
            .as("Verify MstCategory relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCategoryUpdatableRelationshipsEquals(MstCategory expected, MstCategory actual) {}
}
