package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstCountryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCountryAllPropertiesEquals(MstCountry expected, MstCountry actual) {
        assertMstCountryAutoGeneratedPropertiesEquals(expected, actual);
        assertMstCountryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCountryAllUpdatablePropertiesEquals(MstCountry expected, MstCountry actual) {
        assertMstCountryUpdatableFieldsEquals(expected, actual);
        assertMstCountryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCountryAutoGeneratedPropertiesEquals(MstCountry expected, MstCountry actual) {
        assertThat(expected)
            .as("Verify MstCountry auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCountryUpdatableFieldsEquals(MstCountry expected, MstCountry actual) {
        assertThat(expected)
            .as("Verify MstCountry relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getUnm49Code()).as("check unm49Code").isEqualTo(actual.getUnm49Code()))
            .satisfies(e -> assertThat(e.getIsoAlpha2Code()).as("check isoAlpha2Code").isEqualTo(actual.getIsoAlpha2Code()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstCountryUpdatableRelationshipsEquals(MstCountry expected, MstCountry actual) {
        assertThat(expected)
            .as("Verify MstCountry relationships")
            .satisfies(e -> assertThat(e.getRegion()).as("check region").isEqualTo(actual.getRegion()));
    }
}
