package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstDriverAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstDriverAllPropertiesEquals(MstDriver expected, MstDriver actual) {
        assertMstDriverAutoGeneratedPropertiesEquals(expected, actual);
        assertMstDriverAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstDriverAllUpdatablePropertiesEquals(MstDriver expected, MstDriver actual) {
        assertMstDriverUpdatableFieldsEquals(expected, actual);
        assertMstDriverUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstDriverAutoGeneratedPropertiesEquals(MstDriver expected, MstDriver actual) {
        assertThat(expected)
            .as("Verify MstDriver auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstDriverUpdatableFieldsEquals(MstDriver expected, MstDriver actual) {
        assertThat(expected)
            .as("Verify MstDriver relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getContactNumber()).as("check contactNumber").isEqualTo(actual.getContactNumber()))
            .satisfies(e -> assertThat(e.getVehicleDetails()).as("check vehicleDetails").isEqualTo(actual.getVehicleDetails()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstDriverUpdatableRelationshipsEquals(MstDriver expected, MstDriver actual) {}
}
