package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstLoyaltyProgramAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstLoyaltyProgramAllPropertiesEquals(MstLoyaltyProgram expected, MstLoyaltyProgram actual) {
        assertMstLoyaltyProgramAutoGeneratedPropertiesEquals(expected, actual);
        assertMstLoyaltyProgramAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstLoyaltyProgramAllUpdatablePropertiesEquals(MstLoyaltyProgram expected, MstLoyaltyProgram actual) {
        assertMstLoyaltyProgramUpdatableFieldsEquals(expected, actual);
        assertMstLoyaltyProgramUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstLoyaltyProgramAutoGeneratedPropertiesEquals(MstLoyaltyProgram expected, MstLoyaltyProgram actual) {
        assertThat(expected)
            .as("Verify MstLoyaltyProgram auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstLoyaltyProgramUpdatableFieldsEquals(MstLoyaltyProgram expected, MstLoyaltyProgram actual) {
        assertThat(expected)
            .as("Verify MstLoyaltyProgram relevant properties")
            .satisfies(e -> assertThat(e.getPointsEarned()).as("check pointsEarned").isEqualTo(actual.getPointsEarned()))
            .satisfies(e -> assertThat(e.getMembershipTier()).as("check membershipTier").isEqualTo(actual.getMembershipTier()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstLoyaltyProgramUpdatableRelationshipsEquals(MstLoyaltyProgram expected, MstLoyaltyProgram actual) {
        assertThat(expected)
            .as("Verify MstLoyaltyProgram relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()));
    }
}
