package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstPostalCodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstPostalCodeAllPropertiesEquals(MstPostalCode expected, MstPostalCode actual) {
        assertMstPostalCodeAutoGeneratedPropertiesEquals(expected, actual);
        assertMstPostalCodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstPostalCodeAllUpdatablePropertiesEquals(MstPostalCode expected, MstPostalCode actual) {
        assertMstPostalCodeUpdatableFieldsEquals(expected, actual);
        assertMstPostalCodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstPostalCodeAutoGeneratedPropertiesEquals(MstPostalCode expected, MstPostalCode actual) {
        assertThat(expected)
            .as("Verify MstPostalCode auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstPostalCodeUpdatableFieldsEquals(MstPostalCode expected, MstPostalCode actual) {
        assertThat(expected)
            .as("Verify MstPostalCode relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstPostalCodeUpdatableRelationshipsEquals(MstPostalCode expected, MstPostalCode actual) {
        assertThat(expected)
            .as("Verify MstPostalCode relationships")
            .satisfies(e -> assertThat(e.getSubDistrict()).as("check subDistrict").isEqualTo(actual.getSubDistrict()));
    }
}
