package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstRegionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstRegionAllPropertiesEquals(MstRegion expected, MstRegion actual) {
        assertMstRegionAutoGeneratedPropertiesEquals(expected, actual);
        assertMstRegionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstRegionAllUpdatablePropertiesEquals(MstRegion expected, MstRegion actual) {
        assertMstRegionUpdatableFieldsEquals(expected, actual);
        assertMstRegionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstRegionAutoGeneratedPropertiesEquals(MstRegion expected, MstRegion actual) {
        assertThat(expected)
            .as("Verify MstRegion auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstRegionUpdatableFieldsEquals(MstRegion expected, MstRegion actual) {
        assertThat(expected)
            .as("Verify MstRegion relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getUnm49Code()).as("check unm49Code").isEqualTo(actual.getUnm49Code()))
            .satisfies(e -> assertThat(e.getIsoAlpha2Code()).as("check isoAlpha2Code").isEqualTo(actual.getIsoAlpha2Code()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstRegionUpdatableRelationshipsEquals(MstRegion expected, MstRegion actual) {}
}
