package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstSubDistrictAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstSubDistrictAllPropertiesEquals(MstSubDistrict expected, MstSubDistrict actual) {
        assertMstSubDistrictAutoGeneratedPropertiesEquals(expected, actual);
        assertMstSubDistrictAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstSubDistrictAllUpdatablePropertiesEquals(MstSubDistrict expected, MstSubDistrict actual) {
        assertMstSubDistrictUpdatableFieldsEquals(expected, actual);
        assertMstSubDistrictUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstSubDistrictAutoGeneratedPropertiesEquals(MstSubDistrict expected, MstSubDistrict actual) {
        assertThat(expected)
            .as("Verify MstSubDistrict auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstSubDistrictUpdatableFieldsEquals(MstSubDistrict expected, MstSubDistrict actual) {
        assertThat(expected)
            .as("Verify MstSubDistrict relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getUnm49Code()).as("check unm49Code").isEqualTo(actual.getUnm49Code()))
            .satisfies(e -> assertThat(e.getIsoAlpha2Code()).as("check isoAlpha2Code").isEqualTo(actual.getIsoAlpha2Code()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstSubDistrictUpdatableRelationshipsEquals(MstSubDistrict expected, MstSubDistrict actual) {
        assertThat(expected)
            .as("Verify MstSubDistrict relationships")
            .satisfies(e -> assertThat(e.getDistrict()).as("check district").isEqualTo(actual.getDistrict()));
    }
}
