package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MstTaskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstTaskAllPropertiesEquals(MstTask expected, MstTask actual) {
        assertMstTaskAutoGeneratedPropertiesEquals(expected, actual);
        assertMstTaskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstTaskAllUpdatablePropertiesEquals(MstTask expected, MstTask actual) {
        assertMstTaskUpdatableFieldsEquals(expected, actual);
        assertMstTaskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstTaskAutoGeneratedPropertiesEquals(MstTask expected, MstTask actual) {
        assertThat(expected)
            .as("Verify MstTask auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstTaskUpdatableFieldsEquals(MstTask expected, MstTask actual) {
        assertThat(expected)
            .as("Verify MstTask relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMstTaskUpdatableRelationshipsEquals(MstTask expected, MstTask actual) {
        assertThat(expected)
            .as("Verify MstTask relationships")
            .satisfies(e -> assertThat(e.getJobs()).as("check jobs").isEqualTo(actual.getJobs()));
    }
}
