package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostalCodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostalCodeAllPropertiesEquals(PostalCode expected, PostalCode actual) {
        assertPostalCodeAutoGeneratedPropertiesEquals(expected, actual);
        assertPostalCodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostalCodeAllUpdatablePropertiesEquals(PostalCode expected, PostalCode actual) {
        assertPostalCodeUpdatableFieldsEquals(expected, actual);
        assertPostalCodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostalCodeAutoGeneratedPropertiesEquals(PostalCode expected, PostalCode actual) {
        assertThat(expected)
            .as("Verify PostalCode auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostalCodeUpdatableFieldsEquals(PostalCode expected, PostalCode actual) {
        assertThat(expected)
            .as("Verify PostalCode relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostalCodeUpdatableRelationshipsEquals(PostalCode expected, PostalCode actual) {
        assertThat(expected)
            .as("Verify PostalCode relationships")
            .satisfies(e -> assertThat(e.getSubDistrict()).as("check subDistrict").isEqualTo(actual.getSubDistrict()));
    }
}
