package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAllPropertiesEquals(Services expected, Services actual) {
        assertServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAllUpdatablePropertiesEquals(Services expected, Services actual) {
        assertServiceUpdatableFieldsEquals(expected, actual);
        assertServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAutoGeneratedPropertiesEquals(Services expected, Services actual) {
        assertThat(expected)
            .as("Verify Service auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceUpdatableFieldsEquals(Services expected, Services actual) {
        assertThat(expected)
            .as("Verify Service relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getDurationInHours()).as("check durationInHours").isEqualTo(actual.getDurationInHours()))
            .satisfies(e -> assertThat(e.getServiceType()).as("check serviceType").isEqualTo(actual.getServiceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceUpdatableRelationshipsEquals(Services expected, Services actual) {
        assertThat(expected)
            .as("Verify Service relationships")
            .satisfies(e -> assertThat(e.getTestimonial()).as("check testimonial").isEqualTo(actual.getTestimonial()));
    }
}
