package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubDistrictAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubDistrictAllPropertiesEquals(SubDistrict expected, SubDistrict actual) {
        assertSubDistrictAutoGeneratedPropertiesEquals(expected, actual);
        assertSubDistrictAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubDistrictAllUpdatablePropertiesEquals(SubDistrict expected, SubDistrict actual) {
        assertSubDistrictUpdatableFieldsEquals(expected, actual);
        assertSubDistrictUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubDistrictAutoGeneratedPropertiesEquals(SubDistrict expected, SubDistrict actual) {
        assertThat(expected)
            .as("Verify SubDistrict auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubDistrictUpdatableFieldsEquals(SubDistrict expected, SubDistrict actual) {
        assertThat(expected)
            .as("Verify SubDistrict relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubDistrictUpdatableRelationshipsEquals(SubDistrict expected, SubDistrict actual) {
        assertThat(expected)
            .as("Verify SubDistrict relationships")
            .satisfies(e -> assertThat(e.getDistrict()).as("check district").isEqualTo(actual.getDistrict()));
    }
}
